# Generated by Django 3.2.8 on 2022-02-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='SalesModel',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='StoreModel',
            new_name='Store',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-brand',)},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-date', '-store_id', '-product_id')},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('-country', '-state')},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
