# Generated by Django 3.2.8 on 2021-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'blooddonor',
            },
        ),
    ]
