# Generated by Django 3.2.8 on 2021-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(default='O+', max_length=10),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
