# Generated by Django 3.2.8 on 2021-11-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0002_auto_20211128_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonor',
            name='gender',
        ),
    ]
