# Generated by Django 3.2.8 on 2021-11-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0005_alter_blooddonor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(choices=[('A+', '1'), ('A−', '2'), ('B+', '3'), ('B−', '4'), ('AB+', '5'), ('AB−', '6'), ('O+', '7'), ('O−', '8')], max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=10),
        ),
    ]
