# Generated by Django 3.2.8 on 2021-11-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_instagram_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instagram',
            table='instagram',
        ),
    ]
