# Generated by Django 3.2.8 on 2021-12-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_instagram_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='password',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instagram',
            old_name='username',
            new_name='regnum',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='description',
        ),
    ]
