# Generated by Django 3.1.6 on 2021-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('passwd', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('landproperty', models.CharField(max_length=100)),
            ],
        ),
    ]
