# Generated by Django 3.2.8 on 2022-02-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FancyStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'facystore',
                'ordering': ('item_id',),
            },
        ),
    ]
